on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      API_URL: 'https://api.integ.inno.cybeats.com/'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Import a cyclonedx SBOM of a application
        uses: cybeats/sbom-studio-action@v1
        with:
          url: ${{ env.API_URL }}
          filePath: ./examples/acme-tools-github-2.4.3-cyclonedx.json 
          secretAccessKey: ${{ secrets.SECRETKEY }}  
          accessKey: ${{ secrets.ACCESSKEY }}  
          subType: application  
